version: 3.3

services:
    server:
        build: api/.

        environment:
            - GUNICORN_CMD_ARGS="--reload"
          volumes:
            - ./api:/api
          command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8000
          env_file:
            - ./api/.env
          ports:
            - 8000:8000
          depends_on:
            - postgres

    postgres:
        image: postgres:13-alpine
        volumes:
            - $HOME/postgres_hf/data:/var/lib/postgresql/data
            - $HOME/data:/data
          env_file:
            - api/.env
          ports:
            - 5432:5432
        pgadmin:
          container_name: pgadmin
          image: dpage/pgadmin4
          environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=admin
          ports:
            - "5050:80"